import type { SiteContent } from './defaultSiteContent'

export const publishedSiteContent: SiteContent | null = {
  "home": {
    "heroLine1": "Art",
    "heroLine2": "Direction",
    "heroTagline": "Art direction & AI crafted for premium brands",
    "heroLocation": "Thibaud Fossati - Paris",
    "projectsTitle": "Projects",
    "servicesTitle": "Services",
    "servicesIntro": "For premium brands seeking distinctive art direction, shaped by 15 years of experience and AI as a creative medium.",
    "services": [
      {
        "name": "Art direction",
        "desc": "Visual identity, campaigns, Key visuals"
      },
      {
        "name": "AI Creativity",
        "desc": "Images and videos generated by AI"
      },
      {
        "name": "Social media",
        "desc": "Content strategy and production"
      },
      {
        "name": "Web design",
        "desc": "Interfaces, UX, digital experiences"
      },
      {
        "name": "Motion design",
        "desc": "Animation, Video, reels"
      },
      {
        "name": "Editing",
        "desc": "Post-production, retouching, color grading"
      }
    ],
    "aboutEyebrow": "Thibaud Fossati · Paris",
    "aboutQuote": "Artificial intelligence doesn’t replace creativity. It amplifies it.",
    "aboutCtaLabel": "About",
    "contactCtaTitle": "At InStories, technology serves ideas, aesthetics and storytelling.\n\nDesign first. \nVision always.",
    "contactCtaButton": "Contact",
    "instagramPostUrls": [
      "https://www.instagram.com/p/DIGtjSAuzCK/",
      "https://www.instagram.com/p/C4IdfDEritC/",
      "https://www.instagram.com/p/CnrSpJWIh8Z/"
    ]
  },
  "about": {
    "name": "Thibaud\nFossati",
    "roleLine": "Art Director · AI Creativity · Paris",
    "estLabel": "Est. 2009",
    "splitDarkLabel": "15+ years · Premium brands",
    "splitIntro": "Independent art director based in Paris, Thibaud Fossati has spent 15 years collaborating with the world's leading agencies — Publicis, TBWA, BBDO, Ogilvy, DDB — for brands that demand creative excellence.\n\nHis signature: rigorous art direction, shaped by a constant curiosity for new visual forms. Since the emergence of generative AI, he has made it a central tool in his practice — not to replace vision, but to amplify it.\n\nAt InStories, every project starts from a conviction: the best brands don't just communicate. They tell stories.",
    "skills": [
      "Art direction",
      "AI Creativity",
      "Motion design",
      "Web design"
    ],
    "manifestoQuote": "\"Crafting pipeline narratives\n& visuals for luxury brands.\"",
    "stats": [
      {
        "value": "15+",
        "label": "Years"
      },
      {
        "value": "50+",
        "label": "Brands"
      },
      {
        "value": "10",
        "label": "Agencies"
      }
    ],
    "agencies": [
      "Publicis",
      "TBWA",
      "BBDO",
      "Ogilvy",
      "DDB"
    ],
    "ctaTitle": "Let's work together",
    "ctaLabel": "Contact"
  },
  "contact": {
    "title": "Contact",
    "email": "contact@instories.fr",
    "phone": "06 03 36 18 36",
    "addressLines": [
      "72, rue des Archives",
      "75003 Paris, France"
    ],
    "socials": [
      {
        "label": "Instagram",
        "href": "https://www.instagram.com/instories_ai"
      },
      {
        "label": "TikTok",
        "href": "https://tiktok.com/@ghost.in.gloss"
      }
    ],
    "availabilityLabel": "Available",
    "availabilityText": "Tell me about your project, and let us create something remarkable together."
  },
  "footer": {
    "copyright": "© InStories 2026",
    "registration": "RCS 850 498 635 R.C.S. Paris",
    "socials": [
      {
        "label": "Instagram",
        "href": "https://www.instagram.com/instories_ai"
      },
      {
        "label": "TikTok",
        "href": "https://tiktok.com/@ghost.in.gloss"
      },
      {
        "label": "Linkedin",
        "href": "https://www.linkedin.com/in/thibaud-fossati-44902412/"
      }
    ]
  },
  "pdfReminder": {
    "isEnabled": false,
    "triggerProjectViews": 5,
    "title": "Receive the InStories summary?",
    "description": "After viewing these Projects, keep the essentials: download the InStories summary.",
    "ctaLabel": "Download the PDF file",
    "pdfUrl": "/pdf/instories-dossier.pdf?v=1774987345287"
  },
  "design": {
    "displayFont": "gloock",
    "displayWeight": 100,
    "displaySize": 75,
    "displayLetterSpacing": 0.029,
    "displayWordSpacing": 0.128,
    "displayLineHeight": 0.88,
    "displayCase": "uppercase",
    "displayEmphasis": "important-italic",
    "colorModePreference": "light",
    "colorMode": "light",
    "nightStyle": "safe",
    "displayProfiles": {
      "gloock": {
        "displayWeight": 100,
        "displaySize": 75,
        "displayLetterSpacing": 0.029,
        "displayWordSpacing": 0.128,
        "displayLineHeight": 0.88,
        "displayCase": "uppercase",
        "displayEmphasis": "important-italic"
      },
      "cormorant": {
        "displayWeight": 400,
        "displaySize": 75,
        "displayLetterSpacing": 0.029,
        "displayWordSpacing": 0.128,
        "displayLineHeight": 0.88,
        "displayCase": "uppercase",
        "displayEmphasis": "important-italic"
      },
      "roboto": {
        "displayWeight": 400,
        "displaySize": 75,
        "displayLetterSpacing": 0.029,
        "displayWordSpacing": 0.128,
        "displayLineHeight": 0.88,
        "displayCase": "uppercase",
        "displayEmphasis": "important-italic"
      }
    }
  },
  "projects": [
    {
      "id": "onlyone-art-of-dynamic-sports-design",
      "client": "ONLYONE",
      "title": "The Art of Dynamic Sports Design",
      "tagline": "Sports brand & digital platform",
      "status": "published",
      "order": 0,
      "category": [
        "Logo design",
        "Motion identity",
        "Website"
      ],
      "year": "2022",
      "agencies": [
        "Website",
        "Social media"
      ],
      "description": "Blind logo design & motion identity. Identity revealed through movement, rhythm and form.",
      "brief": "Creative exploration for a sports identity system designed to move across website and social formats.",
      "deliverables": [
        "Logo system",
        "Motion identity",
        "Website complet",
        "Social media assets"
      ],
      "tools": [
        "Brand design",
        "Motion design",
        "Digital design"
      ],
      "cover": "/media/projects/onlyone-art-of-dynamic-sports-design/cover.webp",
      "images": [
        "/media/projects/onlyone-art-of-dynamic-sports-design/image-01.webp"
      ],
      "videoUrl": "/media/projects/onlyone-art-of-dynamic-sports-design/video-01.mp4",
      "videoUrls": [
        "/media/projects/onlyone-art-of-dynamic-sports-design/video-01.mp4",
        "/videos/onlyone-cloud-built-people.mp4"
      ],
      "videoPlacements": [
        "grid",
        "grid"
      ],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": true,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#e7e7e8",
      "imageAspectRatios": [
        "16 / 9"
      ],
      "videoAspectRatios": [
        "16 / 9",
        "16 / 9"
      ],
      "coverFocalPoint": {
        "x": 51,
        "y": 50
      },
      "videoAutoplay": [
        true,
        true
      ],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/media/projects/onlyone-art-of-dynamic-sports-design/image-01.webp"
          ],
          "imageAspectRatios": [
            "16 / 9"
          ]
        }
      ]
    },
    {
      "id": "armani-beauty",
      "client": "Armani Beauty",
      "title": "Crema Nera",
      "tagline": "The remodeling sheer cream",
      "status": "published",
      "order": 1,
      "category": [
        "Art direction",
        "AI Creativity"
      ],
      "year": "2024",
      "agencies": [
        "L'Oréal Luxe"
      ],
      "description": "Art direction for the launch of Crema Nera — luxury, materiality, light.",
      "brief": "Elevate the product in all its complexity. Show formula, texture, Armani elegance.",
      "deliverables": [
        "Product visuals",
        "Social media",
        "Digital campaign"
      ],
      "tools": [
        "Art direction",
        "AI Creativity",
        "Editing"
      ],
      "cover": "/media/projects/armani-beauty/cover.webp",
      "images": [
        "/media/projects/armani-beauty/image-01.webp",
        "/media/projects/armani-beauty/image-02.webp",
        "/media/projects/armani-beauty/cover.webp",
        "/media/projects/armani-beauty/image-04.webp"
      ],
      "videoUrl": "",
      "videoUrls": [],
      "videoPlacements": [],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": false,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#f0ede8",
      "coverFocalPoint": {
        "x": 44.46227929373997,
        "y": 13.741751382200821
      },
      "imageAspectRatios": [
        "1 / 1",
        "1 / 1",
        "4 / 5",
        "1 / 1"
      ],
      "videoAspectRatios": [],
      "videoAutoplay": [],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/media/projects/armani-beauty/image-01.webp",
            "/media/projects/armani-beauty/image-02.webp",
            "/media/projects/armani-beauty/cover.webp"
          ],
          "imageAspectRatios": [
            "1 / 1",
            "1 / 1",
            "4 / 5"
          ]
        },
        {
          "id": "block-1774902818820-2",
          "images": [
            "/media/projects/armani-beauty/image-04.webp"
          ],
          "imageAspectRatios": [
            "1 / 1"
          ]
        }
      ]
    },
    {
      "id": "nespresso-fusalp",
      "client": "Nespresso × Fusalp",
      "title": "Taste The Winter Wonder",
      "tagline": "Luxury alpine collaboration",
      "status": "published",
      "order": 2,
      "category": [
        "Art direction",
        "Social media"
      ],
      "year": "2023",
      "agencies": [
        "Ogilvy Paris"
      ],
      "description": "Collaboration between Nespresso and Fusalp — alpine luxury, coffee, and performance.",
      "brief": "Merge two premium worlds into one cohesive, desirable visual identity.",
      "deliverables": [
        "Social media",
        "Key visuals",
        "Motion design"
      ],
      "tools": [
        "Art direction",
        "Social media",
        "Motion design"
      ],
      "cover": "/media/projects/nespresso-fusalp/cover.webp",
      "images": [
        "/media/projects/nespresso-fusalp/image-01.webp",
        "/media/projects/nespresso-fusalp/image-02.webp",
        "/media/projects/nespresso-fusalp/image-03.webp",
        "/media/projects/nespresso-fusalp/image-04.webp"
      ],
      "videoUrl": "/videos/nespresso-fusalp.mp4",
      "videoUrls": [
        "/videos/nespresso-fusalp.mp4"
      ],
      "videoPlacements": [
        "full"
      ],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": false,
        "muted": true,
        "loop": true,
        "aspectRatio": "1 / 1"
      },
      "color": "#e5e8ed",
      "coverFocalPoint": {
        "x": 50,
        "y": 50
      },
      "imageAspectRatios": [
        "16 / 9",
        "16 / 9",
        "16 / 9",
        "16 / 9"
      ],
      "videoAspectRatios": [
        "4 / 5"
      ],
      "videoAutoplay": [
        true
      ],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/media/projects/nespresso-fusalp/image-01.webp",
            "/media/projects/nespresso-fusalp/image-02.webp",
            "/media/projects/nespresso-fusalp/image-03.webp",
            "/media/projects/nespresso-fusalp/image-04.webp"
          ],
          "imageAspectRatios": [
            "16 / 9",
            "16 / 9",
            "16 / 9",
            "16 / 9"
          ]
        }
      ]
    },
    {
      "id": "granier",
      "client": "Garnier",
      "title": "Ultra Doux",
      "tagline": "Nature & performance",
      "status": "published",
      "order": 3,
      "category": [
        "Art direction",
        "Social media"
      ],
      "year": "2025",
      "agencies": [
        "L'Oréal"
      ],
      "description": "Revamp of Ultra Doux social communication — natural, inclusive, modern.",
      "brief": "Rejuvenate Garnier Ultra Doux on social media without losing its natural territory.",
      "deliverables": [
        "Social media",
        "Content series",
        "Motion design"
      ],
      "tools": [
        "Art direction",
        "AI Creativity",
        "Social media"
      ],
      "cover": "/media/projects/granier/cover.webp",
      "images": [
        "/media/projects/granier/image-01.webp",
        "/media/projects/granier/image-02.webp"
      ],
      "videoUrl": "/media/projects/granier/video-01.mp4",
      "videoUrls": [
        "/media/projects/granier/video-01.mp4",
        "/media/projects/granier/video-02.mp4"
      ],
      "videoPlacements": [
        "right",
        "left"
      ],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": false,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#e8f0e5",
      "coverFocalPoint": {
        "x": 50,
        "y": 48
      },
      "imageAspectRatios": [
        "1 / 1",
        "1 / 1"
      ],
      "videoAspectRatios": [
        "9 / 16",
        "9 / 16"
      ],
      "videoAutoplay": [
        true,
        true
      ],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/media/projects/granier/image-01.webp",
            "/media/projects/granier/image-02.webp"
          ],
          "imageAspectRatios": [
            "1 / 1",
            "1 / 1"
          ]
        }
      ]
    },
    {
      "id": "salomon",
      "client": "Salomon",
      "title": "Tomorrow Is Yours",
      "tagline": "Trail running art direction",
      "status": "published",
      "order": 4,
      "category": [
        "Art direction",
        "Motion design"
      ],
      "year": "2022",
      "agencies": [
        "DDB Paris"
      ],
      "description": "Trail running campaign for Salomon — raw, earthy, in-motion art direction.",
      "brief": "Position Salomon as the future trail brand. Energy, performance, authenticity.",
      "deliverables": [
        "Campagne Social media",
        "Motion design",
        "Key visuals"
      ],
      "tools": [
        "Art direction",
        "AI Creativity",
        "Motion design"
      ],
      "cover": "/media/projects/salomon/cover.webp",
      "images": [
        "/media/projects/salomon/image-01.webp",
        "/media/projects/salomon/image-02.webp",
        "/media/projects/salomon/image-03.webp",
        "/media/projects/salomon/image-04.webp",
        "/media/projects/salomon/image-05.webp",
        "/media/projects/salomon/image-06.webp"
      ],
      "videoUrl": "/media/projects/salomon/video-01.mp4",
      "videoUrls": [
        "/media/projects/salomon/video-01.mp4"
      ],
      "videoPlacements": [
        "full"
      ],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": true,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#e8e0d5",
      "coverFocalPoint": {
        "x": 50.16556291390728,
        "y": 39.55573951434879
      },
      "imageAspectRatios": [
        "9 / 16",
        "9 / 16",
        "9 / 16",
        "9 / 16",
        "9 / 16",
        "16 / 9"
      ],
      "videoAspectRatios": [
        "16 / 9"
      ],
      "videoAutoplay": [
        true
      ],
      "imageBlocks": [
        {
          "id": "block-1774984979060-2",
          "images": [
            "/media/projects/salomon/image-01.webp",
            "/media/projects/salomon/image-02.webp",
            "/media/projects/salomon/image-03.webp",
            "/media/projects/salomon/image-04.webp",
            "/media/projects/salomon/image-05.webp"
          ],
          "imageAspectRatios": [
            "9 / 16",
            "9 / 16",
            "9 / 16",
            "9 / 16",
            "9 / 16"
          ]
        },
        {
          "id": "block-1774985643096-2",
          "images": [
            "/media/projects/salomon/image-06.webp"
          ],
          "imageAspectRatios": [
            "16 / 9"
          ]
        }
      ]
    },
    {
      "id": "estee-lauder",
      "client": "Estée Lauder",
      "title": "Advanced Night Repair",
      "tagline": "For beautiful skin, timing is everything",
      "status": "published",
      "order": 5,
      "category": [
        "Art direction",
        "Web design"
      ],
      "year": "2020",
      "agencies": [
        "Estée Lauder Company"
      ],
      "description": "360° campaign for the Advanced Night Repair — digital, OOH, social.",
      "brief": "Modernize the iconic ANR serum for a digital-first audience while preserving the luxury DNA.",
      "deliverables": [
        "OOH campaign",
        "Social media",
        "Emailing",
        "Motion design"
      ],
      "tools": [
        "Art direction",
        "Web design",
        "Editing"
      ],
      "cover": "https://www.sephora.fr/on/demandware.static/-/Library-Sites-SephoraV2/default/dw9e3580f1/brands/BrandUniverse/ESTEE_LAUDER/branduniverse2/1_ESTEE_LAUDER_690_483_type1_1.jpg",
      "images": [
        "/images/estee-cover.jpg",
        "https://www.sephora.fr/on/demandware.static/-/Library-Sites-SephoraV2/default/dw9e3580f1/brands/BrandUniverse/ESTEE_LAUDER/branduniverse2/1_ESTEE_LAUDER_690_483_type1_1.jpg"
      ],
      "videoUrl": "",
      "videoUrls": [],
      "videoPlacements": [],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": false,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#eceaf5",
      "coverFocalPoint": {
        "x": 53.807947019867555,
        "y": 75.46449595290655
      },
      "imageAspectRatios": [
        "16 / 9",
        "4 / 5"
      ],
      "videoAspectRatios": [],
      "videoAutoplay": [],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/images/estee-cover.jpg",
            "https://www.sephora.fr/on/demandware.static/-/Library-Sites-SephoraV2/default/dw9e3580f1/brands/BrandUniverse/ESTEE_LAUDER/branduniverse2/1_ESTEE_LAUDER_690_483_type1_1.jpg"
          ],
          "imageAspectRatios": [
            "16 / 9",
            "4 / 5"
          ]
        }
      ]
    },
    {
      "id": "project-1774860856037",
      "client": "VICHY MINERAL 89",
      "title": "Daily booster & cream",
      "tagline": "AI-driven product exploration — liquid & mineral textures",
      "status": "published",
      "order": 6,
      "category": [
        "Creative direction",
        "AI-driven visual exploration"
      ],
      "year": "2024",
      "agencies": [
        "L'Oréal Active Cosmetics"
      ],
      "description": "Creative direction & AI-driven visual exploration for beauty products.",
      "brief": "Daily booster & cream explores liquid and mineral textures through a visual direction enhanced by AI for premium skincare.",
      "deliverables": [
        "Creative direction",
        "AI visual exploration",
        "Beauty product stills"
      ],
      "tools": [
        "Creative direction",
        "AI image generation",
        "Post-production"
      ],
      "cover": "/media/projects/project-1774860856037/cover.webp",
      "coverFocalPoint": {
        "x": 49.668874172185426,
        "y": 50.15176600441501
      },
      "images": [
        "/media/projects/project-1774860856037/image-01.webp",
        "/media/projects/project-1774860856037/cover.webp",
        "/media/projects/project-1774860856037/image-03.webp"
      ],
      "imageAspectRatios": [
        "16 / 9",
        "4 / 5",
        "16 / 9"
      ],
      "videoUrl": "/media/projects/project-1774860856037/video-01.mp4",
      "videoUrls": [
        "/media/projects/project-1774860856037/video-01.mp4"
      ],
      "videoAspectRatios": [
        "16 / 9"
      ],
      "videoPlacements": [
        "full"
      ],
      "videoOptions": {
        "mode": "native",
        "minimal": false,
        "autoplay": false,
        "muted": true,
        "loop": true,
        "aspectRatio": "16 / 9"
      },
      "color": "#f3efe7",
      "videoAutoplay": [
        true
      ],
      "imageBlocks": [
        {
          "id": "block-1",
          "images": [
            "/media/projects/project-1774860856037/image-01.webp",
            "/media/projects/project-1774860856037/cover.webp",
            "/media/projects/project-1774860856037/image-03.webp"
          ],
          "imageAspectRatios": [
            "16 / 9",
            "4 / 5",
            "16 / 9"
          ]
        }
      ]
    }
  ]
} as SiteContent
